# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shoufei_ui.ui'
#
# Created: Sat Jul 29 20:15:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 1021, 187))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.chepai_qian = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chepai_qian.sizePolicy().hasHeightForWidth())
        self.chepai_qian.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.chepai_qian.setFont(font)
        self.chepai_qian.setObjectName("chepai_qian")
        self.horizontalLayout.addWidget(self.chepai_qian)
        self.chepai_zimu = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.chepai_zimu.setFont(font)
        self.chepai_zimu.setObjectName("chepai_zimu")
        self.horizontalLayout.addWidget(self.chepai_zimu)
        self.chepai_hou = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.chepai_hou.setFont(font)
        self.chepai_hou.setObjectName("chepai_hou")
        self.horizontalLayout.addWidget(self.chepai_hou)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cheliang_leixing = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cheliang_leixing.setFont(font)
        self.cheliang_leixing.setObjectName("cheliang_leixing")
        self.horizontalLayout_2.addWidget(self.cheliang_leixing)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dianhua = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.dianhua.setFont(font)
        self.dianhua.setObjectName("dianhua")
        self.horizontalLayout_2.addWidget(self.dianhua)
        self.is_kefu = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.is_kefu.setFont(font)
        self.is_kefu.setObjectName("is_kefu")
        self.horizontalLayout_2.addWidget(self.is_kefu)
        self.is_zhuanru = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.is_zhuanru.setFont(font)
        self.is_zhuanru.setObjectName("is_zhuanru")
        self.horizontalLayout_2.addWidget(self.is_zhuanru)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.anjianshoufei_xiangmu = QtGui.QComboBox(self.layoutWidget)
        self.anjianshoufei_xiangmu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anjianshoufei_xiangmu.sizePolicy().hasHeightForWidth())
        self.anjianshoufei_xiangmu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.anjianshoufei_xiangmu.setFont(font)
        self.anjianshoufei_xiangmu.setObjectName("anjianshoufei_xiangmu")
        self.horizontalLayout_3.addWidget(self.anjianshoufei_xiangmu)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.weiqishoufei_xiangmu = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weiqishoufei_xiangmu.sizePolicy().hasHeightForWidth())
        self.weiqishoufei_xiangmu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.weiqishoufei_xiangmu.setFont(font)
        self.weiqishoufei_xiangmu.setObjectName("weiqishoufei_xiangmu")
        self.horizontalLayout_4.addWidget(self.weiqishoufei_xiangmu)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.zongjian_xiangmu = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zongjian_xiangmu.sizePolicy().hasHeightForWidth())
        self.zongjian_xiangmu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.zongjian_xiangmu.setFont(font)
        self.zongjian_xiangmu.setObjectName("zongjian_xiangmu")
        self.horizontalLayout_7.addWidget(self.zongjian_xiangmu)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.qita_xiangmu1 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qita_xiangmu1.sizePolicy().hasHeightForWidth())
        self.qita_xiangmu1.setSizePolicy(sizePolicy)
        self.qita_xiangmu1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qita_xiangmu1.setFont(font)
        self.qita_xiangmu1.setObjectName("qita_xiangmu1")
        self.horizontalLayout_6.addWidget(self.qita_xiangmu1)
        self.qitajine_1 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.qitajine_1.setFont(font)
        self.qitajine_1.setObjectName("qitajine_1")
        self.horizontalLayout_6.addWidget(self.qitajine_1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.qita_xiangmu2 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qita_xiangmu2.sizePolicy().hasHeightForWidth())
        self.qita_xiangmu2.setSizePolicy(sizePolicy)
        self.qita_xiangmu2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qita_xiangmu2.setFont(font)
        self.qita_xiangmu2.setObjectName("qita_xiangmu2")
        self.horizontalLayout_6.addWidget(self.qita_xiangmu2)
        self.qitajine_2 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qitajine_2.setFont(font)
        self.qitajine_2.setObjectName("qitajine_2")
        self.horizontalLayout_6.addWidget(self.qitajine_2)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.qita_xiangmu3 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qita_xiangmu3.sizePolicy().hasHeightForWidth())
        self.qita_xiangmu3.setSizePolicy(sizePolicy)
        self.qita_xiangmu3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qita_xiangmu3.setFont(font)
        self.qita_xiangmu3.setObjectName("qita_xiangmu3")
        self.horizontalLayout_6.addWidget(self.qita_xiangmu3)
        self.qitajine_3 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qitajine_3.setFont(font)
        self.qitajine_3.setObjectName("qitajine_3")
        self.horizontalLayout_6.addWidget(self.qitajine_3)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.qita_xiangmu4 = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qita_xiangmu4.sizePolicy().hasHeightForWidth())
        self.qita_xiangmu4.setSizePolicy(sizePolicy)
        self.qita_xiangmu4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qita_xiangmu4.setFont(font)
        self.qita_xiangmu4.setObjectName("qita_xiangmu4")
        self.horizontalLayout_6.addWidget(self.qita_xiangmu4)
        self.qitajine_4 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.qitajine_4.setFont(font)
        self.qitajine_4.setObjectName("qitajine_4")
        self.horizontalLayout_6.addWidget(self.qitajine_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.fukuanfangshi = QtGui.QComboBox(self.layoutWidget)
        self.fukuanfangshi.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.fukuanfangshi.setFont(font)
        self.fukuanfangshi.setObjectName("fukuanfangshi")
        self.horizontalLayout_8.addWidget(self.fukuanfangshi)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.pingzhenghao = QtGui.QLineEdit(self.layoutWidget)
        self.pingzhenghao.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.pingzhenghao.setFont(font)
        self.pingzhenghao.setObjectName("pingzhenghao")
        self.horizontalLayout_8.addWidget(self.pingzhenghao)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.label_xianjin = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_xianjin.setFont(font)
        self.label_xianjin.setText("")
        self.label_xianjin.setObjectName("label_xianjin")
        self.horizontalLayout_8.addWidget(self.label_xianjin)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.label_weixin = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_weixin.setFont(font)
        self.label_weixin.setText("")
        self.label_weixin.setObjectName("label_weixin")
        self.horizontalLayout_8.addWidget(self.label_weixin)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.label_zhifubao = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_zhifubao.setFont(font)
        self.label_zhifubao.setText("")
        self.label_zhifubao.setObjectName("label_zhifubao")
        self.horizontalLayout_8.addWidget(self.label_zhifubao)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.label_yufufeika = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_yufufeika.setFont(font)
        self.label_yufufeika.setText("")
        self.label_yufufeika.setObjectName("label_yufufeika")
        self.horizontalLayout_8.addWidget(self.label_yufufeika)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.label_yinhangka = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_yinhangka.setFont(font)
        self.label_yinhangka.setText("")
        self.label_yinhangka.setObjectName("label_yinhangka")
        self.horizontalLayout_8.addWidget(self.label_yinhangka)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.lcdNumber.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Al Bayan")
        font.setPointSize(60)
        font.setWeight(75)
        font.setBold(True)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setNumDigits(5)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_10.addWidget(self.lcdNumber)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(2, 197, 1021, 461))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setMaximumSize(QtCore.QSize(60, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.chaxun_chepai_qian = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaxun_chepai_qian.sizePolicy().hasHeightForWidth())
        self.chaxun_chepai_qian.setSizePolicy(sizePolicy)
        self.chaxun_chepai_qian.setMaximumSize(QtCore.QSize(60, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.chaxun_chepai_qian.setFont(font)
        self.chaxun_chepai_qian.setObjectName("chaxun_chepai_qian")
        self.horizontalLayout_11.addWidget(self.chaxun_chepai_qian)
        self.chaxun_chepai_zimu = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaxun_chepai_zimu.sizePolicy().hasHeightForWidth())
        self.chaxun_chepai_zimu.setSizePolicy(sizePolicy)
        self.chaxun_chepai_zimu.setMaximumSize(QtCore.QSize(60, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chaxun_chepai_zimu.setFont(font)
        self.chaxun_chepai_zimu.setObjectName("chaxun_chepai_zimu")
        self.horizontalLayout_11.addWidget(self.chaxun_chepai_zimu)
        self.chaxun_chepai_hou = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaxun_chepai_hou.sizePolicy().hasHeightForWidth())
        self.chaxun_chepai_hou.setSizePolicy(sizePolicy)
        self.chaxun_chepai_hou.setMaximumSize(QtCore.QSize(16777215, 20))
        self.chaxun_chepai_hou.setSizeIncrement(QtCore.QSize(91, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.chaxun_chepai_hou.setFont(font)
        self.chaxun_chepai_hou.setObjectName("chaxun_chepai_hou")
        self.horizontalLayout_11.addWidget(self.chaxun_chepai_hou)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.chaxun_shoufeixiangmu = QtGui.QComboBox(self.layoutWidget1)
        self.chaxun_shoufeixiangmu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaxun_shoufeixiangmu.sizePolicy().hasHeightForWidth())
        self.chaxun_shoufeixiangmu.setSizePolicy(sizePolicy)
        self.chaxun_shoufeixiangmu.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chaxun_shoufeixiangmu.setFont(font)
        self.chaxun_shoufeixiangmu.setObjectName("chaxun_shoufeixiangmu")
        self.horizontalLayout_11.addWidget(self.chaxun_shoufeixiangmu)
        self.is_time = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.is_time.setFont(font)
        self.is_time.setObjectName("is_time")
        self.horizontalLayout_11.addWidget(self.is_time)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.start_dateTimeEdit = QtGui.QDateTimeEdit(self.layoutWidget1)
        self.start_dateTimeEdit.setObjectName("start_dateTimeEdit")
        self.horizontalLayout_11.addWidget(self.start_dateTimeEdit)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.end_dateTimeEdit = QtGui.QDateTimeEdit(self.layoutWidget1)
        self.end_dateTimeEdit.setObjectName("end_dateTimeEdit")
        self.horizontalLayout_11.addWidget(self.end_dateTimeEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button_shoukuan = QtGui.QPushButton(self.layoutWidget1)
        self.button_shoukuan.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_shoukuan.setFont(font)
        self.button_shoukuan.setObjectName("button_shoukuan")
        self.horizontalLayout_12.addWidget(self.button_shoukuan)
        self.button_chexiao = QtGui.QPushButton(self.layoutWidget1)
        self.button_chexiao.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_chexiao.setFont(font)
        self.button_chexiao.setObjectName("button_chexiao")
        self.horizontalLayout_12.addWidget(self.button_chexiao)
        self.button_chaxun = QtGui.QPushButton(self.layoutWidget1)
        self.button_chaxun.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_chaxun.setFont(font)
        self.button_chaxun.setObjectName("button_chaxun")
        self.horizontalLayout_12.addWidget(self.button_chaxun)
        self.button_tuikuan = QtGui.QPushButton(self.layoutWidget1)
        self.button_tuikuan.setEnabled(False)
        self.button_tuikuan.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_tuikuan.setFont(font)
        self.button_tuikuan.setObjectName("button_tuikuan")
        self.horizontalLayout_12.addWidget(self.button_tuikuan)
        self.button_dayin = QtGui.QPushButton(self.layoutWidget1)
        self.button_dayin.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_dayin.setFont(font)
        self.button_dayin.setObjectName("button_dayin")
        self.horizontalLayout_12.addWidget(self.button_dayin)
        self.button_biaojikaipiao = QtGui.QPushButton(self.layoutWidget1)
        self.button_biaojikaipiao.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_biaojikaipiao.setFont(font)
        self.button_biaojikaipiao.setObjectName("button_biaojikaipiao")
        self.horizontalLayout_12.addWidget(self.button_biaojikaipiao)
        self.button_jiezhang = QtGui.QPushButton(self.layoutWidget1)
        self.button_jiezhang.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_jiezhang.setFont(font)
        self.button_jiezhang.setObjectName("button_jiezhang")
        self.horizontalLayout_12.addWidget(self.button_jiezhang)
        self.button_xiugaimima = QtGui.QPushButton(self.layoutWidget1)
        self.button_xiugaimima.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_xiugaimima.setFont(font)
        self.button_xiugaimima.setObjectName("button_xiugaimima")
        self.horizontalLayout_12.addWidget(self.button_xiugaimima)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.line_2 = QtGui.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.liebiao_table = QtGui.QTableWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liebiao_table.sizePolicy().hasHeightForWidth())
        self.liebiao_table.setSizePolicy(sizePolicy)
        self.liebiao_table.setMinimumSize(QtCore.QSize(0, 360))
        self.liebiao_table.setMaximumSize(QtCore.QSize(1019, 360))
        self.liebiao_table.setObjectName("liebiao_table")
        self.liebiao_table.setColumnCount(0)
        self.liebiao_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.liebiao_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "车牌号：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "车辆类型：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "车主电话：", None, QtGui.QApplication.UnicodeUTF8))
        self.is_kefu.setText(QtGui.QApplication.translate("MainWindow", "客服", None, QtGui.QApplication.UnicodeUTF8))
        self.is_zhuanru.setText(QtGui.QApplication.translate("MainWindow", "转入", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "安检项目：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "尾气项目：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "综检项目：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "其他1：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "其他2：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "其他3：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "其他4：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "付款方式:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "凭证号", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "现金：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "微信：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", " 支付宝：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", " 预付费卡：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", " 银行卡：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "车牌号：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "检验类别：", None, QtGui.QApplication.UnicodeUTF8))
        self.is_time.setText(QtGui.QApplication.translate("MainWindow", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "开始时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "截止时间", None, QtGui.QApplication.UnicodeUTF8))
        self.button_shoukuan.setText(QtGui.QApplication.translate("MainWindow", "收款", None, QtGui.QApplication.UnicodeUTF8))
        self.button_chexiao.setText(QtGui.QApplication.translate("MainWindow", "撤销", None, QtGui.QApplication.UnicodeUTF8))
        self.button_chaxun.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.button_tuikuan.setText(QtGui.QApplication.translate("MainWindow", "退款", None, QtGui.QApplication.UnicodeUTF8))
        self.button_dayin.setText(QtGui.QApplication.translate("MainWindow", "打印", None, QtGui.QApplication.UnicodeUTF8))
        self.button_biaojikaipiao.setText(QtGui.QApplication.translate("MainWindow", "标记开票", None, QtGui.QApplication.UnicodeUTF8))
        self.button_jiezhang.setText(QtGui.QApplication.translate("MainWindow", "当日结账", None, QtGui.QApplication.UnicodeUTF8))
        self.button_xiugaimima.setText(QtGui.QApplication.translate("MainWindow", "修改密码", None, QtGui.QApplication.UnicodeUTF8))

